/*  - mission.h
 *
 * firmware - By astrobyte 18/03/26.
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 *
 */
#ifndef FIRMWARE_MISSION_H
#define FIRMWARE_MISSION_H
#include <Arduino.h>
#define MAX_PAYLOAD_CHUNK 128
#define SPACECRAFT_ID 0x01

#define SC_TM_ID_ACCE_X 0x01
#define SC_TM_ID_ACCE_Y 0x02
#define SC_TM_ID_ACCE_Z 0x03
#define SC_TM_ID_ACCE_TMP 0x04

#define SC_TM_ID_BME_TEMPERATURE 0x05
#define SC_TM_ID_BME_PRESSURE 0x06
#define SC_TM_ID_BME_ALTITUDE 0x07
#define SC_TM_ID_BME_HUMIDITY 0x08

#define SC_TM_ID_SIM_THRUSTER0 0x09
#define SC_TM_ID_SIM_THRUSTER1 0x0A

/* APIDS TC */
// C&DH
#define SPP_APID_TC_GET_UPTIME 0x01
#define SPP_APID_TC_GET_RESETC 0x02
// EPS
#define SPP_APID_TC_GET_EPS_STATUS 0x03
#define SPP_APID_TC_GET_EPS_BATTERY 0x04
// Payload
#define SPP_APID_TC_BROADCAST_MSG 0x05
#define SPP_APID_TC_GET_TEMP 0x06
#define SPP_APID_TC_GET_GYRO 0x07
#define SPP_APID_TC_GET_TM 0x08
// SOFTWARE / MAINTENANCE
#define SPP_APID_TC_REBOOT 0x09
#define SPP_APID_TC_SEND_FW 0x10
#define SPP_APID_TC_DUMP_MEM 0x11
// AUTH
#define SPP_APID_TC_GET_AES 0x12
// DEBUG
#define SPP_APID_TC_PING 0x13

/* APIDS TM */
// C&DH
#define SPP_APID_TM_SEND_UPTIME 0x1001
#define SPP_APID_TM_SEND_RESETC 0x1002
// EPS
#define SPP_APID_TM_SEND_EPS_STATUS 0x2003
#define SPP_APID_TM_SEND_EPS_BATTERY 0x2004
// Payload
#define SPP_APID_TM_SEND_BROADCAST 0x3005
#define SPP_APID_TM_SEND_TEMP 0x3006
#define SPP_APID_TM_SEND_GYRO 0x3007
#define SPP_APID_TM_SEND_TM 0x3008
// SOFTWARE / MAINTENANCE
#define SPP_APID_TM_SEND_FIRMWARE 0x4010
#define SPP_APID_TM_SEND_DUMP_MEM 0x4011
// AUTH
#define SPP_APID_TM_SEND_AES 0x5012
// DEBUG
#define SPP_APID_TM_SEND_PING 0x6013

#endif // FIRMWARE_MISSION_H