; PlatformIO Project Configuration File
;
; FlatSat Firmware - RP2040 custom board
; Flash: 4MB, Boot2: generic SPI /4

[env:flatsat_rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico
framework = arduino
board_build.core = earlephilhower
board_build.flash_size = 4MB
board_upload.maximum_size = 4194304
board_build.filesystem_size = 0.5m
board_build.boot2 = boot2_generic_03h_4_padded_checksum
lib_deps =
    jgromes/RadioLib@^7.2.1
    adafruit/Adafruit BME280 Library@^2.3.0
    adafruit/Adafruit Unified Sensor@^1.1.14
    sparkfun/SparkFun LIS2DH12 Arduino Library@^1.0.4
    adafruit/Adafruit TinyUSB Library@^3.4.4
